apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-prom-app
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-app
        image: shubhamdeshmukh/go-prometheus-app
        ports:
        - name: web
          containerPort: 8080